export interface TutoringArea {
  id: number;
  name: string;
  subjects: string[];
}

export const TUTORING_AREAS: TutoringArea[] = [
  {
    id: 1,
    name: "Business",
    subjects: [
      "Accounting",
      "Advertising",
      "Business",
      "Business Law",
      "Business Plans",
      "Data Analytics",
      "Entrepreneurship",
      "Excel",
      "Management",
      "Marketing",
      "Risk Management",
      "Supply Chain",
    ],
  },
  {
    id: 2,
    name: "Mathematics",
    subjects: [
      "Algebra",
      "Calculus",
      "Geometry",
      "Trigonometry",
      "Statistics",
      "Discrete Mathematics",
    ],
  },
  {
    id: 3,
    name: "Programming",
    subjects: [
      "C /C++ Programming",
      "C#",
      "Java",
      "Python",
      "JavaScript",
      "HTML/CSS",
      "PHP",
      "SQL",
      "R",
      "Linux / Shell Scripting",
      "Android studio",
    ],
  },
  {
    id: 4,
    name: "Science",
    subjects: [
      "Biology",
      "Chemistry",
      "Physics",
      "Environmental Science",
      "Earth Science",
      "Astronomy",
    ],
  },
  {
    id: 5,
    name: "Writing",
    subjects: [
      "Academic Writing",
      "Creative Writing",
      "Technical Writing",
      "Essay Writing",
      "Report Writing",
      "Research Papers",
    ],
  },
  {
    id: 6,
    name: "Health & Medical",
    subjects: [
      "Anatomy",
      "Physiology",
      "Radiology",
      "Pharmacology",
      "Nursing",
      "Public Health",
    ],
  },
  {
    id: 7,
    name: "Economics",
    subjects: [
      "Microeconomics",
      "Macroeconomics",
      "Finance",
      "International Economics",
      "Public Economics",
      "Economic Policy",
    ],
  },
  {
    id: 8,
    name: "Engineering",
    subjects: [
      "Aeronautical Engineering",
      "Chemical Engineering",
      "Civil Engineering",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Environmental Engineering",
      "Biomedical Engineering",
    ],
  },
  {
    id: 9,
    name: "Computer Science",
    subjects: [
      "Algorithms",
      "Data Structures",
      "Database Management",
      "Operating Systems",
      "Software Engineering",
      "Computer Networks",
      "Cybersecurity",
      "Cryptography",
      "Mobile Development",
      "UI Design",
    ],
  },
  {
    id: 10,
    name: "Art and Humanities",
    subjects: [
      "Art",
      "Law",
      "Foreign Languages",
      "Cultural Studies",
      "Dance",
      "English",
      "Ethnic Studies",
      "Fashion Design",
      "Film",
      "Geography",
      "Global Studies",
      "Graphic Design",
      "History",
      "Interior Design",
      "Landscape Architecture",
      "Latin American Studies",
      "Linguistics",
      "Literature",
      "Music",
      "Philosophy",
      "Political Science",
      "Psychology",
      "Religion",
      "Social Science",
      "Sociology",
      "Urban Planning",
      "Women's Studies",
    ],
  },
];
